version: '3'
services:

  app:
    build:
      args:
        user: Abdelrazek
        uid: 1000
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    networks:
      - fitcmp-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - fitcmp-network

  mysql:
    image: mariadb:10.5.8
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3307"
    networks:
      - fitcmp-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=64M
    networks:
      - fitcmp-network


volumes:
  mysqldata:

networks:
  fitcmp-network:
    driver: bridge

